export const pokemonTypes = [
  { name: 'fire', icon: '🔥' },
  { name: 'water', icon: '💧' },
  { name: 'grass', icon: '🌿' },
  { name: 'electric', icon: '⚡' },
  { name: 'psychic', icon: '🔮' },
  { name: 'ice', icon: '❄️' },
  { name: 'dragon', icon: '🐉' },
  { name: 'dark', icon: '🌑' },
  { name: 'fairy', icon: '🧚' },
  { name: 'normal', icon: '🟤' },
  { name: 'fighting', icon: '🥋' },
  { name: 'flying', icon: '🕊️' },
  { name: 'poison', icon: '☠️' },
  { name: 'ground', icon: '🏜️' },
  { name: 'rock', icon: '🪨' },
  { name: 'bug', icon: '🐛' },
  { name: 'ghost', icon: '👻' },
  { name: 'steel', icon: '🛠️' },
];