export const pokemonTypes = [
  { name: 'fire', icon: '🔥', color: '#FFA756' },
  { name: 'water', icon: '💧', color: '#58ABF6' },
  { name: 'grass', icon: '🌿', color: '#8BBE8A' },
  { name: 'electric', icon: '⚡', color: '#F4D23C' },
  { name: 'psychic', icon: '🔮', color: '#FF6568' },
  { name: 'ice', icon: '❄️', color: '#7ED4E6' },
  { name: 'dragon', icon: '🐉', color: '#7B62A3' },
  { name: 'dark', icon: '🌑', color: '#6E5A72' },
  { name: 'fairy', icon: '🧚', color: '#FDB9E9' },
  { name: 'normal', icon: '🟤', color: '#A4ACAF' },
  { name: 'fighting', icon: '🥋', color: '#D3425F' },
  { name: 'flying', icon: '🕊️', color: '#A891EC' },
  { name: 'poison', icon: '☠️', color: '#B763CF' },
  { name: 'ground', icon: '🏜️', color: '#DA7C4D' },
  { name: 'rock', icon: '🪨', color: '#C7B78B' },
  { name: 'bug', icon: '🐛', color: '#A8B820' },
  { name: 'ghost', icon: '👻', color: '#70559B' },
  { name: 'steel', icon: '🛠️', color: '#B8B8D0' },
];